[package]
name = "valkyrie"
authors = ["James R Swift"]
version = "0.1.1"
entrypoint = "src/lib.typ"
exclude = ["./README.md"]
keywords = ["type", "validation", "zod"]
license = "GPL-3.0-only"
repository = "https://github.com/JamesxX/valkyrie"
description = "Type validation"
